config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    get 'games/index'
  end
  devise_for :users, controllers: {
    :sessions => "users/sessions",
    :registrations => "users/registrations" }

  resources :profile_pictures, only: %i[new create edit update]

  root to: "pages#home"
  get "accueil", to: "pages#accueil"

  get 'users/:id/games', to: 'users/games#index'

  resources :leagues, only: %i[new create show index] do
    member do
      get 'choose_mode'
      post 'choose_mode_create'
      get 'choose_teams'
      post 'choose_teams_create'
    end
    resources :team_users, only: %i[new create]
    resources :games, only: %i[show edit index]
    resources :messages, only: %i[create index]
  end

  resources :users, only: %i[show]

  get "/community", to: "invitations#community", as: :community
  resources :invitations, only: :create

# get '/leagues/:id/team_users/new', to: 'team_users#new'   --- could be a path to any custom mehtod

  resources :games, only: %i[new create show update] do
    member do
      get 'choose_game_teams'
      post 'choose_game_teams_create'
    end
  end
  resources :fields, only: :index

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :league
  belongs_to :user

  validates :comment, length: { in: 1..1000 }
  # validates :comment, length: { minimum: 1 }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @league = League.find(params[:league_id])
    @message = Message.new
  end

  def create
    @league = League.find(params[:league_id])
    @message = Message.new(message_params)
    @message.league = @league
    @message.user = current_user
    @message.save
    redirect_to league_messages_path(@league)
  end

  private

  def message_params
    params.require(:message).permit(:comment)
  end
end

app/views/messages/index.html.erb
<h2 class="bar light-blue-bar">
  <%= @league.name.upcase %>
</h2>

<ul class="nav nav-pills nav-fill" style="margin-bottom:10px">
  <li class="nav-item yellow-box" >
    <%= link_to "CLASSEMENT", league_path(@league) %>
  </li>
  <li class="nav-item yellow-box" >
    <%= link_to "MATCHS", league_games_path(@league) %>
  </li>
  <li class="nav-item yellow-box active">
    <%= link_to "MUR", league_messages_path(@league) %>
  </li>
</ul>

<div class="chatroom">
  <div class="chatroom-item">
    <%= simple_form_for [@league, @message] do |f| %>
      <%= f.input :comment, placeholder: "Hey les gars, qui est parti avec mes boules la dernière fois ?", label: false, input_html: { id: "form-message"} %>
      <%= f.button :submit, value:'ENVOYER', class:"btn-small btn-smally", id:"btn-message" %>
    <% end %>
  </div>
  <div class="chatroom-display">
    <% @league.messages.reverse.each do |message| %>
      <% if message.user == current_user %>
        <div class="card-chat card-chat-reverse">
          <div class="message-avatar-date message-reverse">
            <%= image_tag current_user.profile_pic, class: "avatar-yellow avatar-medium avatar-poto-message avatar-reverse"%><span class= "username-comment username-reverse"><%= message.user.username.upcase %></span>
            <p class="message-light-grey message-reverse"> <%= message.created_at.strftime("%d" +"/" + "%m" +"/" + "%Y") %>
                                                           <%= message.created_at.strftime("%H"+":"+ "%M") %></p>
          </div>
          <p class="message-content-blue"><%= message.comment %></p>
        </div>
      <% else %>
        <div class="card-chat">
          <div class="message-avatar-date">
            <%= image_tag message.user.profile_pic, class: "avatar-blue avatar-medium avatar-poto-message"%><span class= "username-comment"><%= message.user.username.upcase%></span>
            <p class="message-light-grey"> <%= message.created_at.strftime("%d" +"/" + "%m" +"/" + "%Y") %>
                                           <%= message.created_at.strftime("%H"+":"+ "%M") %></p>
          </div>
          <p class="message-content-blue"><%= message.comment %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>