config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    get 'games/index'
  end
  devise_for :users, controllers: {
    :sessions => "users/sessions",
    :registrations => "users/registrations" }

  resources :profile_pictures, only: %i[new create edit update]

  root to: "pages#home"
  get "accueil", to: "pages#accueil"

  get 'users/:id/games', to: 'users/games#index'

  resources :leagues, only: %i[new create show index] do
    member do
      get 'choose_mode'
      post 'choose_mode_create'
      get 'choose_teams'
      post 'choose_teams_create'
    end
    resources :team_users, only: %i[new create]
    resources :games, only: %i[show edit index]
    resources :messages, only: %i[create index]
  end

  resources :users, only: %i[show]

  get "/community", to: "invitations#community", as: :community
  resources :invitations, only: :create

# get '/leagues/:id/team_users/new', to: 'team_users#new'   --- could be a path to any custom mehtod

  resources :games, only: %i[new create show update] do
    member do
      get 'choose_game_teams'
      post 'choose_game_teams_create'
    end
  end
  resources :fields, only: :index

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/league.rb
class League < ApplicationRecord
  validates :name, presence: true
  validates :name, length: { in: 3..25 }
  has_many :games
  has_many :teams
  has_many :team_users, through: :teams
  has_many :messages
  has_many :selected_users
  has_many :users, through: :selected_users

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  def index
    @user = current_user
    @leagues = @user.leagues
  end

  def show
    @league = League.find(params[:id])
    @games = @league.games
    @teams_sorted = @league.teams.sort_by { |team| [-team.number_of_wins, -(team.points_for - team.points_against)] }

    return unless @league.status == true

    @first_winner = Team.find(@league.league_winner).users.first
    @second_winner = Team.find(@league.league_winner).users.last
  end

  def new
    @user = current_user
    @league = League.new
    @friends = @user.friends.to_a.push(@user).reverse
  end

  def create
    @league = League.new(league_params)
    @players = params[:user].keys.map { |username| User.find_by(username: username) }
    if @players.size.even? && @players.size > 2 && @players.include?(current_user)
      if @league.save
        @players.each do |player|
          SelectedUser.create(league: @league, user: player)
        end
        redirect_to choose_mode_league_path(@league)
      else
        render :new, status: :unprocessable_entity
      end
    else
      redirect_to new_league_path
      flash[:notice] = 'Il faut un nombre pair de joueurs et que tu en fasses partie'
    end
  end

  def choose_mode
    @league = League.find(params[:id])
  end

  def choose_mode_create
    @league = League.find(params[:id])
    if params[:commit] == "HASARD"
      random
    else
      redirect_to choose_teams_league_path(@league)
    end
  end

  # def random
  #   @league = League.find(params[:id])
  #   @teams = []
  #   @pairs_of_players = @league.selected_users.map(&:user).shuffle.each_slice(2).to_a
  #   @pairs_of_players.each do |pair|
  #     @team = Team.create(league: @league)
  #     pair.each do |player|
  #       TeamUser.create(user: player, team: @team)
  #     end
  #     if @teams.any?
  #       @teams.each do |team|
  #         @game = Game.create(league: @league)
  #         GameTeam.create!(team: team, game: @game)
  #         GameTeam.create!(team: @team, game: @game)
  #       end
  #     end
  #     @teams.push(@team)
  #   end
  #   redirect_to league_games_path(@league)
  # end

  def random
    league = League.find(params[:id])
    players = league.selected_users.map(&:user).shuffle
    teams = []

    players.in_groups_of(2, false) do |pair|
      team = league.teams.create!

      pair.each do |player|
        team.users << player
      end

      teams.each do |other_team|
        league.games.create!(teams: [other_team, team])
      end

      teams << team
    end
    redirect_to league_games_path(league)
  end

  def choose_teams
    @league = League.find(params[:id])
    @players = @league.selected_users.map(&:user)
    @usernames = @players.map(&:username)
    @team_user = TeamUser.new
    @number_of_teams = @players.size / 2
  end

  # def choose_teams_create
  #   @league = League.find(params[:id])
  #   @pairs_of_players = params[:team_user].values.map { |id| User.find(id) }.each_slice(2).to_a
  #   @teams = []
  #   @pairs_of_players.each do |pair|
  #     @team = Team.create(league: @league)
  #     pair.each do |player|
  #       TeamUser.create(user: player, team: @team)
  #     end
  #     if @teams.any?
  #       @teams.each do |team|
  #         @game = Game.create(league: @league)
  #         GameTeam.create!(team: team, game: @game)
  #         GameTeam.create!(team: @team, game: @game)
  #       end
  #     end
  #     @teams.push(@team)
  #   end
  #   redirect_to league_games_path(@league)
  # end

  def choose_teams_create
    league = League.find(params[:id])
    # begin
    #   raise "missing params" if params[:team_user].nil? || params[:team_user].empty?
    player_ids = params[:team_user].values
      # raise "invalid player ids" if player_ids.count {|id| User.find_by(id: id).nil? } > 0
    players = player_ids.map { |id| User.find(id) }
    # rescue StandardError => e
    #   redirect_to league_path(league), alert: e.message
    #   return
    # end

    teams = []
    players.in_groups_of(2, false) do |pair|
      team = league.teams.create!
      pair.each do |player|
        team.users << player
      end

      teams.each do |other_team|
        league.games.create!(teams: [other_team, team])
      end

      teams << team
    end
    redirect_to league_games_path(league)
  end

  private

  def league_params
    params.require(:league).permit(:league_id, :name, :status, :league_winner, :admin_user, :rand, :users)
  end
end

app/views/leagues/choose_mode.html.erb
<h2 class="bar light-blue-bar">CRÉATION DE LIGUE</h2>
<h3 class="bar yellow-bar">3. ES-TU JOUEUR ?</h3>

<div class="flexy choose-mode">
  <%= form_tag(:controller => "leagues", :action => "choose_mode_create", :method => "post", :class => "nifty_form") do %>
  <h3>”Non je ne suis pas zinzin, hors de question que je tombe avec tonton Nanard, il est nul. Je choisis moi même les doublettes”</h3>
    <%= submit_tag("CHOIX", :class => "btn-small btn-smally") %>
  <h3>”Oui j'aime l'aventure, la sauce pimentée, et jouer avec tonton Nanard ne me fait pas peur. Je laisse le hasard faire les doublettes”</h3>
    <%= submit_tag("HASARD", :class => "btn-small btn-smally") %>
  <% end %>
</div>

app/views/leagues/choose_teams.html.erb
<h2 class="bar light-blue-bar">CRÉATION DE LIGUE</h2>
<h3 class="bar yellow-bar">4. JE FORME LES DOUBLETTES</h3>

<div class="flexy choose-teams">
  <%= form_with model: [@league, @team_user], :url =>  choose_teams_create_league_path(@league), :html => {:method => :post} do |f| %>
    <% i = 1 %>
    <% @number_of_teams.times do %>
      <h3><%= "DOUBLETTE n°#{i}" %></h3>
      <div class="doublette-selection">
        <%= f.collection_select "team#{i}user1", @players.map { |player| [player.username.upcase, player.id] }, :second, :first, {}, { class: "btn-doublette" } %>
        <%= f.collection_select "team#{i}user2", @players.map { |player| [player.username.upcase, player.id] }, :second, :first, {}, { class: "btn-doublette" } %>
      </div>
      <% i += 1 %>
    <% end %>
  <div class="flexy">
    <%= f.submit 'FINITO', class: "btn-small btn-smally" %>
  </div>
</div>
  <% end %>

app/views/leagues/index.html.erb
<h2 class= "bar light-blue-bar">MES LIGUES</h2>

<div class="flexy create-league" style="margin-top:15px">
  <%= link_to content_tag(:i, '', class: "fa-solid fa-square-plus fa-square-left") + "NOUVELLE LIGUE" + content_tag(:i, '', class: "fa-solid fa-square-plus fa-square-right"), new_league_path, class: "btn-medium", id: "btn-create" %>
</div>

<div class="flexy">
  <% @leagues.reject { |league| league.status == true }.each do |league| %>
    <%= link_to league.name.upcase , league_path(league), class:"btn-medium" %>
  <% end %>
  <% @leagues.select { |league| league.status == true }.each do |league| %>
    <%= link_to league.name.upcase , league_path(league), class:"btn-medium btn-medium-grey" %>
  <% end %>
</div>

app/views/leagues/new.html.erb
<h3 class="bar light-blue-bar">CRÉATION DE LIGUE</h3>
<h3 class="bar yellow-bar">1. CHOISIS UN NOM</h3>
<div class="container-player-selection">
  <%= simple_form_for @league, html: { class: "form-new-league"} do |f| %>
  <%= f.error_notification %>
    <%= f.input :name,
                label: "Nom de la ligue",
                height: 0,
                input_html: { class: "input-league-name" },
                placeholder: '🚀 La ligue des copains 🚀' %>
  <h3 class="bar yellow-bar bar-inside">2. CHOISIS DES COLLÈGUES</h3>
    <div class="player-selection">
      <% @friends.each do |friend| %>
      <div class="select-player"  data-controller="selection" data-selection-target="player">
        <input type="checkbox" name="user[<%= friend.username%>]" id="<%= friend.username%>" class="check-player" />
        <label class="username-create" data-action="click->selection#background" for="<%= friend.username %>"><%= friend.username.upcase %></label>
        <%= image_tag friend.profile_pic, class: "avatar-blue avatar-small", id: "avatar-background"%>
      </div>
      <% end %>
    </div>
    <%= f.submit 'SUIVANT', class: "btn-small btn-smally" %>
  <% end %>
</div>

app/views/leagues/show.html.erb
<h2 class="bar light-blue-bar">
  <%= @league.name.upcase %>
</h2>

<div >
  <ul class="nav nav-pills nav-fill" style="margin-bottom:10px">
    <li class="nav-item yellow-box active" >
      <%= link_to "CLASSEMENT", league_path(@league) %>
    </li>
    <li class="nav-item yellow-box" >
      <%= link_to "MATCHS", league_games_path(@league) %>
    </li>
    <li class="nav-item yellow-box">
      <%= link_to "MUR", league_messages_path(@league) %>
    </li>
  </ul>

  <% if @league.status == true %>
    <div class="flexy">
      <%= image_tag "crown-victory.png", alt: "Le Wagon", id: "crown-winner" %>
    </div>
    <div class="flexy" id="flex-avatar">
        <% if @first_winner.photo.attached? %>
         <%= cl_image_tag @first_winner.photo.key, class: "avatar-vainqueur" %>
        <% else %>
          <%= image_tag "bobby.png", class: "avatar-vainqueur"%>
        <% end %>
        <% if @second_winner.photo.attached? %>
         <%= cl_image_tag @second_winner.photo.key, class: "avatar-vainqueur" %>
        <% else %>
          <%= image_tag "bobby.png", class: "avatar-vainqueur"%>
        <% end %>
    </div>
  <% end %>

  <div>
    <div class="flexy show-ranking" id="ol-classement">
      <table>
        <tr class="border-ranking">
          <th></th><th>CLASSEMENT</th><th>PTS</th><th>J</th><th>V/D</th><th>DIF</th>
        </tr>
          <% @teams_sorted.each_with_index do |team, index| %>
          <% if team.users.include?(current_user) %>
            <tr class="current-player border-ranking">
              <td class="classement-gras"><%= index + 1 %></td>
              <td class="points-id back-grey"><%= team.users.first.username.upcase %><br><%= team.users.last.username.upcase %><br></td>
              <td class="points-id"><%= team.number_of_wins %></td>
              <td><%= team.games_played %></td>
              <td><%= team.number_of_wins %>/<%= (team.games_played - team.number_of_wins) %></td>
              <% if (team.points_for - team.points_against) > 0 %>
              <td class="diff-id">+<%= (team.points_for - team.points_against) %></td>
              <% else %>
              <td class="diff-id"><%= (team.points_for - team.points_against) %></td>
              <% end %>
            </tr>
          <% else %>
            <tr class="other-players border-ranking">
              <td class="classement-gras"><%= index + 1 %></td>
              <td><%= team.users.first.username.upcase %><br><%= team.users.last.username.upcase %><br></td>
              <td class="points-id back-grey"><%= team.number_of_wins %></td>
              <td><%= team.games_played %></td>
              <td><%= team.number_of_wins %>/<%= (team.games_played - team.number_of_wins) %></td>
              <% if (team.points_for - team.points_against) > 0 %>
              <td class="diff-id">+<%= (team.points_for - team.points_against) %></td>
              <% else %>
              <td class="diff-id"><%= (team.points_for - team.points_against) %></td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>
</div>