config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    get 'games/index'
  end
  devise_for :users, controllers: {
    :sessions => "users/sessions",
    :registrations => "users/registrations" }

  resources :profile_pictures, only: %i[new create edit update]

  root to: "pages#home"
  get "accueil", to: "pages#accueil"

  get 'users/:id/games', to: 'users/games#index'

  resources :leagues, only: %i[new create show index] do
    member do
      get 'choose_mode'
      post 'choose_mode_create'
      get 'choose_teams'
      post 'choose_teams_create'
    end
    resources :team_users, only: %i[new create]
    resources :games, only: %i[show edit index]
    resources :messages, only: %i[create index]
  end

  resources :users, only: %i[show]

  get "/community", to: "invitations#community", as: :community
  resources :invitations, only: :create

# get '/leagues/:id/team_users/new', to: 'team_users#new'   --- could be a path to any custom mehtod

  resources :games, only: %i[new create show update] do
    member do
      get 'choose_game_teams'
      post 'choose_game_teams_create'
    end
  end
  resources :fields, only: :index

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :league, optional: true
  has_many :game_teams
  has_many :teams, through: :game_teams
  has_many :team_users, through: :teams
  has_many :users, through: :team_users
  has_many :selected_players
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @league = League.find(params[:league_id])
    @user = current_user
    @current_user_games = @user.games.where(league: @league)
    @other_games = @league.games.where.not(id: @current_user_games)
  end

  def new
    @game = Game.new
    @user = current_user
    @friends = @user.friends.to_a.push(@user).reverse
  end

  def create
    @game = Game.new
    @players = params[:user].keys.map { |username| User.find_by(username: username) }
    if @players.size == 4 && @players.include?(current_user)
      if @game.save
        @players.each do |player|
          SelectedPlayer.create(game: @game, user: player)
        end
        redirect_to choose_game_teams_game_path(@game)
      else
        render :new, status: :unprocessable_entity
      end
    else
      redirect_to new_game_path
      flash[:notice] = 'Il faut 4 joueurs et que tu sois dans les 4'
    end
  end

  def choose_game_teams
    @game = Game.find(params[:id])
    @players = @game.selected_players.map(&:user)
    @usernames = @players.map(&:username)
    @team_user = TeamUser.new
  end

  def choose_game_teams_create
    @game = Game.find(params[:id])
    @pairs_of_players = params[:team_user].values.map { |id| User.find(id) }.each_slice(2).to_a

    @team_one = Team.create
    @team_two = Team.create

    @pairs_of_players.first.each do |player|
      TeamUser.create(user: player, team: @team_one)
    end

    @pairs_of_players.last.each do |player|
      TeamUser.create(user: player, team: @team_two)
    end

    GameTeam.create!(team: @team_one, game: @game)
    GameTeam.create!(team: @team_two, game: @game)

    if @game.save
      redirect_to game_path(@game)
    else
      redirect_to choose_game_teams_game_path(@game)
    end
  end

  def show
    @game = Game.find(params[:id])
    @team_one = @game.teams.first
    @team_two = @game.teams.last
  end

  def edit
    @game = Game.find(params[:id])
    @team1 = @game.teams.first
    @team2 = @game.teams.last
  end

  def update
    # raise
    @game = Game.find(params[:id])
    @league = @game.league
    @team1 = @game.teams.first
    @team2 = @game.teams.last

    @game.update(game_params)
    if !@game.score_first_team.nil? && !@game.score_second_team.nil?
      if (@game.score_first_team == 13 && @game.score_second_team < 13) || (@game.score_first_team < 13 && @game.score_second_team == 13)

        if @game.score_first_team > @game.score_second_team
          @game.game_winner = @team1.id
          @team1.number_of_wins += 1
        else
          @game.game_winner = @team2.id
          @team2.number_of_wins += 1
        end

        if (@game.score_first_team == 13 && @game.score_second_team == 0) || (@game.score_first_team == 0 && @game.score_second_team == 13)
          badge_first_fanny
        end

        @team1.points_for += @game.score_first_team
        @team1.points_against += @game.score_second_team
        @team1.games_played += 1

        @team2.points_for += @game.score_second_team
        @team2.points_against += @game.score_first_team
        @team2.games_played += 1

        @team2.save
        @team1.save

        @game.status = true
        @game.save

        # fin_de_league
        if @game.league.present?
          @number_of_games_finished = @league.games.where(status: true).count
          @number_total_of_games = @league.games.count
          if @number_of_games_finished == @number_total_of_games
            @league.league_winner = @league.teams.sort_by { |team| [-team.number_of_wins, -(team.points_for - team.points_against)] }.first.id
            @league.status = true
            @league.save
          end

          if @league.status == true
            badge_first_league_winner
            badge_generation
          end

          if @league.status == true
            redirect_to league_path(@league)
          else
            redirect_to league_games_path(@game.league)
          end
        else
          redirect_to game_path(@game)
        end

      else
        # flash[:notice] = 'Score non valide !'
        render :edit, status: :unprocessable_entity
      end
    else
      flash[:notice] = 'Score non valide !'
      render :edit, status: :unprocessable_entity
    end
  end

  def badge_first_league_winner
    @first_vainqueur = Team.find(@league.league_winner).users.first
    @second_vainqueur = Team.find(@league.league_winner).users.last

    if @first_vainqueur.badge.first_league_winner == false
      @first_vainqueur.badge.update!(first_league_winner: true)
      if @first_vainqueur == current_user
        flash[:notice] = 'Nouveau badge débloqué'
      end
    end

    if @second_vainqueur.badge.first_league_winner == false
      @second_vainqueur.badge.update!(first_league_winner: true)
      if @second_vainqueur == current_user
        flash[:notice] = 'Nouveau badge débloqué'
      end
    end
  end

  def badge_generation
    @first_vainqueur = Team.find(@league.league_winner).users.first
    @second_vainqueur = Team.find(@league.league_winner).users.last

    if @first_vainqueur.badge.generation == false && (@first_vainqueur.date_of_birth.year - @second_vainqueur.date_of_birth.year).abs > 30
      @first_vainqueur.badge.update!(generation: true)
      if @first_vainqueur == current_user
        flash[:alert] = 'Nouveau badge débloqué'
      end
    end

    if @second_vainqueur.badge.generation == false && (@first_vainqueur.date_of_birth.year - @second_vainqueur.date_of_birth.year).abs > 30
      @second_vainqueur.badge.update!(generation: true)
      if @second_vainqueur == current_user
        flash[:alert] = 'Nouveau badge débloqué'
      end
    end
  end

  def badge_first_fanny
    if @team1.id == @game.game_winner
      @first_game_winner = @team1.users.first
      @second_game_winner = @team1.users.last
    else
      @first_game_winner = @team2.users.first
      @second_game_winner = @team2.users.last
    end

    if @first_game_winner.badge.first_fanny == false
      @first_game_winner.badge.update!(first_fanny: true)
      if @first_game_winner == current_user
        flash[:notice] = 'Nouveau badge débloqué'
      end
    end

    if @second_game_winner.badge.first_fanny == false
      @second_game_winner.badge.update!(first_fanny: true)
      if @second_game_winner == current_user
        flash[:notice] = 'Nouveau badge débloqué'
      end
    end
  end

  private

  def game_params
    params.require(:game).permit(:score_first_team, :score_second_team, :user, :game_id)
  end
end

app/controllers/users/games_controller.rb
class Users::GamesController < ApplicationController
  def index
    @user = current_user
    @games = @user.games.where(league_id: nil)
    @current_games = @games.where(status: nil)
    @finished_games = @games.where(status: true)
    @league = nil
  end
end

app/views/games/choose_game_teams.html.erb
<h2 class="bar light-blue-bar">NOUVEAU MATCH</h2>
<h3 class="bar yellow-bar">2. JE FORME LES DOUBLETTES</h3>

<div class="flexy choose-teams">
  <%= form_with model: [@game, @team_user], :url =>  choose_game_teams_create_game_path(@game), :html => {:method => :post} do |f| %>
  <h3>DOUBLETTE n°1</h3>
  <div class="doublette-selection">
    <%= f.collection_select "team1user1", @players.map { |player| [player.username.upcase, player.id] }, :second, :first, {}, { class: "btn-doublette" } %>
    <%= f.collection_select "team1user2", @players.map { |player| [player.username.upcase, player.id] }, :second, :first, {}, { class: "btn-doublette" } %>
  </div>
  <h3>DOUBLETTE n°2</h3>
  <div class="doublette-selection">
    <%= f.collection_select "team2user1", @players.map { |player| [player.username.upcase, player.id] }, :second, :first, {}, { class: "btn-doublette" } %>
    <%= f.collection_select "team2user2", @players.map { |player| [player.username.upcase, player.id] }, :second, :first, {}, { class: "btn-doublette" } %>
  </div>
  <div class="flexy">
    <%= f.submit 'JOUER', class: "btn-small btn-smally" %>
  </div>
  <% end %>
</div>

app/views/games/edit.html.erb
<h3 class="bar light-blue-bar">ALORS C'EST QUOI LE SCORE ?</h3>
<div class="edit-score">
  <%= form_with model: @game, html: {class: "edit-score-form"} do |form| %>
    <div class="team-display">
      <% @team1.users.each do |user| %>
      <div class="each-player">
      <% if user == current_user %>
        <%= image_tag user.profile_pic, class: "avatar-yellow avatar-medium avatar-score" %>
      <% else %>
      <%= image_tag user.profile_pic, class: "avatar-blue avatar-medium avatar-score" %>
      <% end %>
        <%= user.username.upcase %>
      </div>
      <% end %>
    </div>
  <%= form.text_area :score_first_team, class: 'score-team'  %>
    <div class="team-display">
      <% @team2.users.each do |user| %>
      <div class="each-player">
      <% if user == current_user %>
        <%= image_tag user.profile_pic, class: "avatar-yellow avatar-medium avatar-score" %>
      <% else %>
      <%= image_tag user.profile_pic, class: "avatar-blue avatar-medium avatar-score" %>
      <% end %>
        <%= user.username.upcase %>
      </div>
        <% end %>
    </div>
    <%= form.text_area :score_second_team, class: 'score-team'  %>
    <br>
    <%= form.submit "VALIDER", class: "btn-small btn-smally" %>
  <% end %>
</div>

app/views/games/index.html.erb
<h2 class="bar light-blue-bar">
  <%= @league.name.upcase %>
</h2>

<ul class="nav nav-pills nav-fill" >
  <li class="nav-item yellow-box" >
    <%= link_to "CLASSEMENT", league_path(@league) %>
  </li>
  <li class="nav-item yellow-box active" >
    <%= link_to "MATCHS", league_games_path(@league) %>
  </li>
  <li class="nav-item yellow-box">
    <%= link_to "MUR", league_messages_path(@league) %>
  </li>
</ul>

<div class="flexy" style="margin-top:20px">
  <% @current_user_games.each do |game| %>
    <% first_team = game.teams.first %>
    <% second_team = game.teams.last %>
        <div class="row row-game">
          <div class="col-4 col-left">
            <% if first_team.users[0] == current_user %>
              <p class="player-actuel"><%= first_team.users[0].username.upcase %><%= image_tag current_user.profile_pic, class: "avatar-yellow avatar-mini" %>
            <% else %>
              <p class="player-actuel"><%= first_team.users[0].username.upcase %>
            <% end %>
            <% if first_team.users[1] == current_user %>
              <p class="player-actuel"><%= first_team.users[1].username.upcase %><%= image_tag current_user.profile_pic, class: "avatar-yellow avatar-mini" %>
            <% else %>
              <p class="player-actuel"><%= first_team.users[1].username.upcase %>
            <% end %>
          </div>
          <div class="col-4 score-color" style="text-align:center">
            <% if game.status == true %>
              <%= game.score_first_team %> - <%= game.score_second_team %>
            <% else %>
              <%= link_to "SCORE ?", edit_league_game_path(@league, game.id), class:"btn-small btn-score" %>
            <% end %>
          </div>
          <div class="col-4 col-right">
            <% if second_team.users[0] == current_user %>
              <p class="player-actuel"><%= second_team.users[0].username.upcase %><%= image_tag current_user.profile_pic, class: "avatar-yellow avatar-mini" %>
            <% else %>
              <p class="player-actuel"><%= second_team.users[0].username.upcase %>
            <% end %>
            <% if second_team.users[1] == current_user %>
              <p class="player-actuel"><%= second_team.users[1].username.upcase %><%= image_tag current_user.profile_pic, class: "avatar-yellow avatar-mini" %>
            <% else %>
              <p class="player-actuel"><%= second_team.users[1].username.upcase %>
            <% end %>
          </div>
        </div>
  <% end %>


  <% @other_games.each do |game| %>
    <% first_team = game.teams.first %>
    <% second_team = game.teams.last %>
        <div class="row row-game">
          <div class="col-4 col-left">
            <% if first_team.users[0] == current_user %>
              <p class="player-actuel"><%= first_team.users[0].username.upcase %><%= image_tag current_user.profile_pic, class: "avatar-yellow avatar-mini" %>
            <% else %>
              <p class="player-actuel"><%= first_team.users[0].username.upcase %>
            <% end %>
            <% if first_team.users[1] == current_user %>
              <p class="player-actuel"><%= first_team.users[1].username.upcase %><%= image_tag current_user.profile_pic, class: "avatar-yellow avatar-mini" %>
            <% else %>
              <p class="player-actuel"><%= first_team.users[1].username.upcase %>
            <% end %>
          </div>
          <div class="col-4 score-color" style="text-align:center">
            <% if game.status == true %>
              <%= game.score_first_team %> - <%= game.score_second_team %>
            <% else %>
              <%= "-" %>
            <% end %>
          </div>
          <div class="col-4 col-right">
            <% if second_team.users[0] == current_user %>
              <p class="player-actuel"><%= second_team.users[0].username.upcase %><%= image_tag current_user.profile_pic, class: "avatar-yellow avatar-mini" %>
            <% else %>
              <p class="player-actuel"><%= second_team.users[0].username.upcase %>
            <% end %>
            <% if second_team.users[1] == current_user %>
              <p class="player-actuel"><%= second_team.users[1].username.upcase %><%= image_tag current_user.profile_pic, class: "avatar-yellow avatar-mini" %>
            <% else %>
              <p class="player-actuel"><%= second_team.users[1].username.upcase %>
            <% end %>
          </div>
        </div>
  <% end %>
</div>

app/views/games/new.html.erb
<h3 class="bar light-blue-bar">NOUVEAU MATCH</h3>
<h3 class="bar yellow-bar">1. CHOISIS 4 COLLÈGUES</h3>
<div class="container-player-selection">
  <%= simple_form_for @game, html: { class: "form-new-league"} do |f| %>
  <div class="player-selection">
      <% @friends.each do |friend| %>
      <div class="select-player"  data-controller="selection" data-selection-target="player">
        <input type="checkbox" name="user[<%=friend.username%>]" id="<%=friend.username%>" class="check-player" />
        <label class="username-create" data-action="click->selection#background" for="<%= friend.username %>"><%= friend.username.upcase %></label>
        <%= image_tag friend.profile_pic, class: "avatar-blue avatar-small", id: "avatar-background"%>
      </div>
    <% end %>
  </div>
  <%= f.submit 'SUIVANT', class: "btn-small btn-smally" %>
    <% end %>
</div>

app/views/games/show.html.erb
<h2 class="bar light-blue-bar">MATCH ONE SHOT</h2>
  <div class="edit-score-form">
    <div class="team-display team-display-one-shot">
      <% @team_one.users.each do |user| %>
      <div class="each-player">
      <% if user == current_user %>
        <%= image_tag user.profile_pic, class: "avatar-yellow avatar-medium avatar-score" %>
      <% else %>
      <%= image_tag user.profile_pic, class: "avatar-blue avatar-medium avatar-score" %>
      <% end %>
        <%= user.username.upcase %>
      </div>
      <% end %>
    </div>

    <div class="flexy" id="score-one-shot">
    <% if @game.status == true %>
      <div class="score-one-shot">
        <h1><%= @game.score_first_team %></h1>
        <h1> ------ </h1>
        <h1><%= @game.score_second_team %></h1>
      </div>
    <% else %>
      <%= link_to "SCORE ?", edit_league_game_path(@game.id), class:"btn-small btn-score" %>
    <% end %>
    </div>
    <div class="team-display team-display-one-shot">
      <% @team_two.users.each do |user| %>
      <div class="each-player">
      <% if user == current_user %>
        <%= image_tag user.profile_pic, class: "avatar-yellow avatar-medium avatar-score" %>
      <% else %>
      <%= image_tag user.profile_pic, class: "avatar-blue avatar-medium avatar-score" %>
      <% end %>
        <%= user.username.upcase %>
      </div>
        <% end %>
    </div>

  </div>